### ISSUE TITLE
Epic: Basic Skeleton Set up

### ISSUE THREAD

**Issue by Tinks18** [Tinks18/Go-Gym#1]
In order to **create basic setup of the django application** as a **developer**, I can **django**

## Acceptance Criteria
* Django framework installed in gitpod successfully

# Tasks
- [x]  Type install command in terminal 
- [x]  Check for the directories in file area 
- [x] Type install libraries commands in terminal
