### ISSUE TITLE
User Story: Install Allauth

### ISSUE THREAD

**Issue by Tinks18** [Tinks18/Go-Gym#15]
As a developer, I need to Install allauth so that users can sign up and access to the app features

## Acceptance Criteria
* install is successful
* displays all the templates 

# Tasks
- [x] Run server
- [x] Create a new username
- [x] Create a new password
- [x] Login 
- [x] Log out
- [x] Add no email required to settings
