### ISSUE TITLE
User Story: Create  username

### ISSUE THREAD

**Issue by Tinks18** [Tinks18/Go-Gym#16]
In order to **check allauth install ** as a **developer**, I can **create a new username **

## Acceptance Criteria
* username is created successfully

# Tasks
- [x] make a new username
- [x] make a new password
- [x] leave the email field blank
- [x] runserver
- [x]  check the home page
