### ISSUE TITLE
 User Story:  Deployment 

### ISSUE THREAD

**Issue by Tinks18** [Tinks18/Go-Gym#4]
In order to **make app available to the user** as a **developer**, I can **deploy app to heroku**

## Acceptance Criteria
* user is able to login/logout
* the app passes all  the basic acceptance criterion

# Tasks
- [x] Create app 
- [x] Update the configuration variables
- [x] Connect to git hub repository
- [x] Choose automatic deploys from github
- [x] Deploy
- [x] View build log
- [x] Confirm deployment
