### ISSUE TITLE
User Story : Basic setup

### ISSUE THREAD

**Issue by Tinks18** [Tinks18/Go-Gym#7]
As a developer, I need to install set up libraries so the project so that basic features are  implemented

## Acceptance Criteria
* basic skeleton project should be successfully created

# Tasks
- [ ] Install Django and gunicorn
- [ ] Install supporting libraries
- [ ] Install Cloudinary Libraries
- [ ] Create requirements file
- [ ] Create Project
- [ ] Create App
- [ ] run server
