### ISSUE TITLE
User Story : Settings

### ISSUE THREAD

**Issue by Tinks18** [Tinks18/Go-Gym#8]
As a developer, I need to update the resources in settings so that images, style and scripts works on the website

## Acceptance Criteria
* the secret keys should be hidden

# Tasks
- [x] Set up environ variables
- [x] Hide secret keys from git pod
- [x] Reference env.py
- [x] Update DataBases Sections
- [x] Add Cloudinary Libraries to installed apps
- [x] Tell Django to use Cloudinary to store media and static files
- [x] Link file to the templates directory in Heroku
- [x] Change the templates directory to TEMPLATES_DIR
- [x] Add Heroku Hostname to ALLOWED_HOSTS
